name: whisper-vf-win
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23
  - pytorch
  - torchaudio
  - pytorch-cuda=12.1
  - ffmpeg
  - git
  - numpy=1.26.*
  - scipy
  - pandas
  - pyyaml
  - tqdm
  - requests
  - pip:
      - openai-whisper
      - speechbrain
      - soundfile
      - huggingface-hub
